<a href="https://colab.research.google.com/github/pameia/tarea/blob/main/practica5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!python --version

Python 3.10.12


In [12]:
import numpy as np
novio=np.array([3,33,333])
print(novio)
print(novio.shape)

[  3  33 333]
(3,)


In [19]:
b=np.zeros((4,6))
b
print(b.shape)
print(b)
b[3,3]=120
print(b)
print(b[:,[2,3]]) #cmbiar columna
print(b[:,[3,2]])

(4, 6)
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 120.   0.   0.]]
[[  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0. 120.]]
[[  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [120.   0.]]


In [37]:
c=np.random.randint(low=4,high=12,size=(2,2))
d=np.random.randint(low=1,high=8,size=(2,2))


In [24]:
c

array([[ 9,  5,  9,  5,  5],
       [ 4,  4,  8,  5, 11],
       [ 9,  9,  5,  4, 10],
       [ 5,  5,  4,  6,  6]])

In [25]:
d

array([[1, 5],
       [1, 5]])

In [38]:
aux=np.vstack((c,d))
print(aux)

[[ 6 11]
 [11  4]
 [ 1  5]
 [ 5  3]]


In [39]:
aux=np.hstack((c,d))
print(aux)

[[ 6 11  1  5]
 [11  4  5  3]]
