<a href="https://colab.research.google.com/github/pameia/tarea/blob/main/TAREAFINAL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

tarea

In [ ]:
import numpy as np

print("NumPy version:", np.version.version)

pass

NumPy version: 1.22.4


In [ ]:
#Create a 1D array of numbers from 0 to 9

arr = np.arange(10)
print(arr)
pass

[0 1 2 3 4 5 6 7 8 9]


In [7]:
#Create a 3×3 numpy array of all True’s
import numpy as np

arra = np.ones((3, 3), dtype=int)
arra = arr.astype(bool)
print(arr)
pass

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [38]:
#Extract all odd numbers from arr
matriz = [[random.randint(1, 10) for j in range(3)] for i in range(3)]
print("Matriz de números aleatorios:")
for fila in matriz:
    print(fila)
# Extraer los números impares de la matriz
impares = []
for fila in matriz:
    for num in fila:
        if num % 2 != 0:
            impares.append(num)
print("Números impares:", impares)

pass

Matriz de números aleatorios:
[8, 5, 8]
[4, 4, 1]
[8, 3, 1]
Números impares: [5, 1, 3, 1]


In [40]:
#Replace all odd numbers in arr with -1
import random

# Crear una matriz de 3x3 con números aleatorios entre 1 y 10
matriz = [[random.randint(1, 10) for j in range(3)] for i in range(3)]
print("Matriz de números aleatorios:")
for fila in matriz:
    print(fila)

# Extraer los números impares de la matriz y reemplazarlos por -1
for i in range(len(matriz)):
    for j in range(len(matriz[i])):
        if matriz[i][j] % 2 != 0:
            matriz[i][j] = -1

print("Matriz con números impares reemplazados por -1:")
for fila in matriz:
    print(fila)
pass

Matriz de números aleatorios:
[2, 9, 5]
[7, 3, 1]
[7, 7, 2]
Matriz con números impares reemplazados por -1:
[2, -1, -1]
[-1, -1, -1]
[-1, -1, 2]


In [47]:
#Convert a 1D array to a 2D array with 2 rows
arr = np.arange(10)
print(arr)
arr = arr.reshape(2, 5)
print(arr)
pass

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [54]:
#Stack arrays a and b vertically
import numpy as np
a = np.random.randint(1, 10, size=(3, 3))
b = np.random.randint(1, 10, size=(3, 3))

print("Matriz a:")
print(a)
print("Matriz b:")
print(b)

# Apilar verticalmente las dos matrices
c = np.vstack((a, b))

print("Matriz c:")
print(c)
print('----')
c=np.random.randint(low=4,high=12,size=(2,2))
d=np.random.randint(low=1,high=8,size=(2,2))
aux=np.vstack((c,d))
print(aux)
pass

Matriz a:
[[5 1 2]
 [1 4 9]
 [1 5 8]]
Matriz b:
[[4 3 6]
 [8 6 9]
 [2 7 3]]
Matriz c:
[[5 1 2]
 [1 4 9]
 [1 5 8]
 [4 3 6]
 [8 6 9]
 [2 7 3]]
----
[[ 4  7]
 [10  4]
 [ 5  1]
 [ 3  2]]


In [56]:
#Stack the arrays a and b horizontally
aux=np.hstack((c,d))
print(aux)
pass

[[ 4  7  5  1]
 [10  4  3  2]]


In [71]:
#Get all items between 5 and 10 from a
import numpy as np
arr = np.arange(10)
# Get all items between 5 and 10
result = arr[arr >= 5]
print(result)
pass

[5 6 7 8 9]


In [ ]:
 #How to make a python function that handles scalars to work on numpy arrays
 # Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])
import numpy as np

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
#maxx(a, b)
tmp=list()
for i in range(7):
  tmp.append(maxx(a[i],b[i]))
print(tmp)



[6, 7, 9, 8, 9, 7, 5]


In [73]:
#Swap columns 1 and 2 in the array arr
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]
b=np.zeros((4,6))
b
print(b.shape)
print(b)
b[3,3]=120
print (b)
print(b[:,[2,3]])
#print (b)

#invertir
print (b)
print(b[:,[3,2]])
#print (b)
pass
 #[[0 1 2]
 #[3 4 5]
# [6 7 8]]


(4, 6)
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 120.   0.   0.]]
[[  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0. 120.]]
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 120.   0.   0.]]
[[  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [120.   0.]]


In [62]:
#Create a 2D array of shape 5x3 to contain random decimal numbers between
# Crear una matriz de 5x3 con números decimales aleatorios entre 5 y 10
import numpy as np
matriz = [[np.random.uniform(5, 10) for j in range(3)] for i in range(5)]
print("Matriz de números decimales aleatorios:")
for fila in matriz:
    print(fila)
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]

Matriz de números decimales aleatorios:
[5.973956457314156, 5.605135121486625, 5.5301381528738425]
[9.570928602308985, 7.037870218065789, 9.25035792440579]
[6.090030551295719, 6.534104244046872, 5.784993292100713]
[6.607067003855336, 9.22191248939291, 7.243878289994963]
[6.421807138315427, 9.312338358315328, 7.746698776723905]
